/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class OmegaHorizonActor extends Actor {
  /** @override */
  prepareDerivedData() {
    super.prepareDerivedData();

    const actorData = this;
    const flags = actorData.flags['omega-horizon'] || {};

    // Make separate methods for each Actor type (character, npc, etc.) to keep
    // things organized.
    this._prepareCharacterData(actorData);
    this._prepareNpcData(actorData);
  }

  /**
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * method allows for different data structures per Actor type.
   * @param {Object} options
   * @returns {Object}
   */
  getRollData(options = {}) {
    const data = super.getRollData(options);
    const rollData = this.system.getRollData?.(options) ?? null;
    return foundry.utils.mergeObject(data, rollData);
  }

  /**
   * Prepare Character type specific data
   */
  _prepareCharacterData(actorData) {
    const data = actorData.system;

    // Make modifications to data here. For example:
    if (data.abilities) {
      for (let [k, v] of Object.entries(data.abilities)) {
        // The minimum value for an ability is 0, unless it is already null.
        if (v.value === null) v.value = 0;
        v.min = 0;
        v.max = 20;

        // Calculate modifier using d20 standards
        v.mod = Math.floor((v.value - 10) / 2);
      }
    }
  }

  /**
   * Prepare NPC type specific data.
   */
  _prepareNpcData(actorData) {
    const data = actorData.system;

    // Make modifications to data here.
  }
}
